project_id = "pgvuicbtevezvusewztx"

[functions.send-push-notification]
verify_jwt = false

[functions.ensure-bee-farmer-article]
verify_jwt = false

[functions.ensure-alsalam-article]
verify_jwt = false

[functions.ensure-africa-child-article]
verify_jwt = false

[functions.ensure-mens-mental-health-article]
verify_jwt = false

[functions.ensure-women-gardening-article]
verify_jwt = false
